<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DockPanelSuite" Version="3.1.1" />
		<PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
		<PackageReference Include="QuickFIXn.Core" Version="1.14.0" />
		<PackageReference Include="QuickFIXn.FIX41" Version="1.14.0" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="System.Reactive" Version="6.1.0" />
	</ItemGroup>

  <ItemGroup>
    <Compile Update="Docking\MyOrders\MyOrdersControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Docking\MyOrders\MyOrdersDock.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Docking\OrderBook\OrderBookControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Docking\OrderBook\OrderBookDock.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Docking\OrderEntry\OrderEntryControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Docking\OrderEntry\OrderEntryDock.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Docking\VerticalBook\VerticalBookControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Docking\VerticalBook\VerticalBookDock.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Main.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>